# Generated by Django 5.0.6 on 2024-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoImersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('origem_demanda', models.CharField(choices=[('PA', 'Pedidos de apoio'), ('PG', 'Pedidos do gabinete'), ('AG', 'Pedidos autogerados')], max_length=2)),
                ('nome_demandante', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
