# Generated by Django 5.0.6 on 2024-07-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('orgao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.orgao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
