# Generated by Django 5.0.6 on 2024-08-06 18:30

import os
from dotenv import load_dotenv
from django.db import migrations
from django.contrib.auth import get_user_model

def create_users(apps, schema_editor):
    User = get_user_model()
    load_dotenv()
    password = os.environ.get('ADMIN_PWD')
    new_users = [
        'yan.carmo@planejamento.mg.gov.br',
        'andre.amorim@planejamento.mg.gov.br',
        'augusta.lamas@planejamento.mg.gov.br',
        'gabriel.dornas@planejamento.mg.gov.br',
        'raiane.souza@seguranca.mg.gov.br',
        'isabelle.oliveira@ca.mg.gov.br',
        'henrique.romano@seguranca.mg.gov.br',
        'henrique.ribeiro@seguranca.mg.gov.br',
        'felipe.simoes@seguranca.mg.gov.br',
    ]
    for user in new_users:
        username = user.split('@')[0]
        if not User.objects.filter(username=username).exists():
            User.objects.create_superuser(
                username=username,
                password=password,
                email=user
            )


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
