# Generated by Django 5.0.6 on 2024-08-06 18:30

import os
from dotenv import load_dotenv
from django.db import migrations
from models.sistema_model import Sistema

def create_systems(apps, schema_editor):
    new_systems = [
        'SIAFI',
        'SIAD',
        'SISAP',
        'GRP',
        'SDAK',
        'SIAUT',
        'PCNET',
        'PORTAL DE COMPRAS',
        'SEI',
    ]
    for system in new_systems:
        if not Sistema.objects.filter(nome=system).exists():
            Sistema.objects.create(
                nome=system
            )


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_add_new_users'),
    ]

    operations = [
        migrations.RunPython(create_systems),
    ]
