# Generated by Django 5.0.6 on 2024-07-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('tempo_execucao_robo', models.IntegerField(blank=True, null=True)),
                ('tempo_execucao_manual', models.IntegerField(blank=True, null=True)),
                ('fase', models.CharField(choices=[('NAOI', 'Não iniciado'), ('EXEC', 'Em execução'), ('CONC', 'Concluído')], max_length=4)),
                ('oportunidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.pedidoimersao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
