# Generated by Django 5.0.6 on 2024-07-23 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_robo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('arrecadacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas_manuais_economizadas', models.IntegerField(blank=True, null=True)),
                ('servidores_reposicionados', models.IntegerField(blank=True, null=True)),
                ('horas_totais_economizadas', models.IntegerField(blank=True, null=True)),
                ('ganho_eficiencia', models.IntegerField(blank=True, null=True)),
                ('oportunidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.pedidoimersao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
