# Generated by Django 5.0.7 on 2024-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_add_new_orgaos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='nivel_prioridade',
            field=models.CharField(blank=True, choices=[('A', 'ALTO'), ('M', 'MÉDIO'), ('B', 'BAIXO')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='nota_prioridade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='telefone_demandante',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
