# Generated by Django 5.0.7 on 2024-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='origem_demanda',
            field=models.CharField(choices=[('PA', 'Pedidos de apoio'), ('PG', 'Pedidos do gabinete'), ('AG', 'Pedidos autogerados'), ('CS', 'Curso')], max_length=2),
        ),
    ]
