# Generated by Django 5.0.7 on 2024-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_pedidoimersao_origem_demanda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoimersao',
            old_name='detalhamento_bd',
            new_name='detalhamento_banco_de_dados',
        ),
        migrations.RenameField(
            model_name='pedidoimersao',
            old_name='existe_bd',
            new_name='existe_banco_de_dados',
        ),
        migrations.RenameField(
            model_name='pedidoimersao',
            old_name='periocdicidade',
            new_name='periodicidade',
        ),
        migrations.RenameField(
            model_name='pedidoimersao',
            old_name='tempo_execucao_manual',
            new_name='tempo_execucao_manual_min',
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='recorrencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
