# Generated by Django 5.0.6 on 2024-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('github_user', models.URLField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
