# Generated by Django 5.0.7 on 2024-09-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_robo_sistema_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robo',
            old_name='tempo_execucao_manual',
            new_name='tempo_execucao_manual_min',
        ),
        migrations.RenameField(
            model_name='robo',
            old_name='tempo_execucao_robo',
            new_name='tempo_execucao_robo_min',
        ),
    ]
