# Generated by Django 5.0.7 on 2024-09-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_rename_detalhamento_bd_pedidoimersao_detalhamento_banco_de_dados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='oportunidade_id',
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='projeto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.projeto'),
        ),
    ]
