# Generated by Django 5.0.7 on 2024-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_projeto_oportunidade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
