# Generated by Django 5.0.7 on 2024-09-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_orgao_nome_alter_orgao_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='projeto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.projeto'),
        ),
    ]
