# Generated by Django 5.0.7 on 2024-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_pedidoimersao_projeto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomanutencao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipeprojeto',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipeprojeto',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidomanutencao',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidomanutencao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetoestrategico',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projetoestrategico',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projetoestrategico',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robo',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='robo',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
