# Generated by Django 5.0.7 on 2024-09-17 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_robo_tempo_execucao_manual_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robo',
            name='tempo_execucao_robo_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
