# Generated by Django 5.0.6 on 2024-07-23 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_pedidomanutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoimersao',
            name='Projeto_estrategico_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.projetoestrategico'),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='conhecimento_automate',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='conhecimento_excel',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='conhecimento_programacao',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='descricao_processo',
            field=models.CharField(default='n/a', max_length=300),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='detalhamento_automacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='detalhamento_bd',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='email_demandante',
            field=models.EmailField(default='n/a', max_length=254),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='existe_automacao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='existe_bd',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='fase',
            field=models.CharField(choices=[('PREC', 'Pedido recebido'), ('PEAN', 'Pedido em análise'), ('PANA', 'Pedido analisado')], default='n/a', max_length=4),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='formato_atendimento',
            field=models.CharField(blank=True, choices=[('IA', 'Imersão automatiza'), ('TV', 'Time volante'), ('CM', 'Curso e mentoria'), ('CU', 'Curso EAD'), ('PE', 'Projeto extensão'), ('ND', 'Não definido')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='impacto_arrecadacao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='link_issue',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='nivel_prioridade',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='nome_processo',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='nota_prioridade',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='orgao_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.orgao'),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='orgao_outros',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='periocdicidade',
            field=models.CharField(choices=[('DIA', 'Diário'), ('SMN', 'Semanal'), ('QUI', 'Quinzenal'), ('MEN', 'Mensal'), ('BIM', 'Bimestral'), ('TRI', 'Trimestral'), ('SMT', 'Semestral'), ('ANU', 'Anual')], default='n/a', max_length=3),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='processo_comum_orgaos',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='projeto_estrategico',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='n/a', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='status',
            field=models.CharField(choices=[('NAN', 'Pedido não analisado'), ('APR', 'Pedido aprovado'), ('ENC', 'Pedido encaminhado'), ('NAT', 'Pedido não atendido')], default='n/a', max_length=4),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='telefone_demandante',
            field=models.CharField(default='n/a', max_length=13),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='tempo_execucao_manual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='usuario_id_apoio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id_apoio', to='models.usuario'),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='usuario_id_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id_principal', to='models.usuario'),
        ),
        migrations.AddField(
            model_name='pedidoimersao',
            name='valor_arrecadacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
