# Generated by Django 5.0.6 on 2024-07-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_pedidoimersao_projeto_estrategico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='nota_prioridade',
            field=models.IntegerField(default=0),
        ),
    ]
