# Generated by Django 5.0.7 on 2024-09-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_robo_tempo_execucao_robo_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('equipe_projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.equipeprojeto')),
                ('robo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.robo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
