# Generated by Django 5.0.6 on 2024-07-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_pedidoimersao_nota_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='Projeto_estrategico_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.projetoestrategico'),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='usuario_id_apoio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id_apoio', to='models.usuario'),
        ),
    ]
