# Generated by Django 5.0.7 on 2024-09-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_equiperobo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='status',
            field=models.CharField(choices=[('NAN', 'PEDIDO NÃO ANALISADO'), ('PRI', 'PRIMEIRO CONTATO'), ('APR', 'PEDIDO APROVADO'), ('ENC', 'PEDIDO ENCAMINHADO'), ('NAT', 'PEDIDO NÃO ATENDIDO')], max_length=4),
        ),
    ]
