# Generated by Django 5.0.6 on 2024-07-31 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_pedidoimersao_projeto_estrategico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='Projeto_estrategico_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.projetoestrategico'),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='orgao_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.orgao'),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='usuario_id_apoio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id_apoio', to='models.usuario'),
        ),
        migrations.AlterField(
            model_name='pedidoimersao',
            name='usuario_id_principal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id_principal', to='models.usuario'),
        ),
    ]
