# Generated by Django 5.0.7 on 2024-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_pedidoimersao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoimersao',
            name='periodicidade',
            field=models.CharField(choices=[('UNI', 'ÚNICO'), ('DIA', 'DIÁRIO'), ('SMN', 'SEMANAL'), ('QUI', 'QUINZENAL'), ('MEN', 'MENSAL'), ('BIM', 'BIMESTRAL'), ('TRI', 'TRIMESTRAL'), ('SMT', 'SEMESTRAL'), ('ANU', 'ANUAL')], max_length=3),
        ),
    ]
